version: 2.1

jobs:
    run_tests:
        docker:
            - image: circleci/node:16.8.0
        steps:
            - checkout
            - run:
              name: Installing dependencies
              command: |
                  npm install --save
            - run:
              name: Running unit tests
              command: |
                  npm run test

workflows:
    my_app_workflow:
        jobs: run_tests
