orbs:
    node: circle/node@2.0.2

version: 2.1

jobs:
    install:
        steps:
            - checkout
            - run: npm install

    test:
        steps:
            - run: npm run test

    build:
        steps:
            - run: npm run build

workflows:
    final:
        jobs:
            - install
            - test
            - build
